textos_gpt={
	"Metrô":[
		("Original", [
				"Sinto sua mão sobre o metal gelado. Seus dedos roçam os meus ao acaso transpirando seu calor na minha pele.",
				"Logo a barra esquenta e tenho que trocar a mão de lugar. Odeio a sensação de alumínio requentado sobre a pele. Não tenho mais muitos espaços disponíveis e me forço a me contentar com a distância.",
				"Te olho. Tão longe e tão perto. Os resquícios da noite estampados no borrado do seu delineado. Te admiro, pasmo, do sapato mal preso ao último fio revolto do penteado.",
				"Nossos olhares se cruzam e você me lança um sorriso cansado que atravessa o ruído do vagão e me laça no esmo do trem.",
				"Nossos corpos são espremidos um contra o outro involuntariamente e sinto uma vontade súbita de cair. Meus órgãos fraquejam, queimando do esforço contínuo. E sinto as últimas notas do seu perfume.",
				"Alcanço a sua mão livre com a minha mão livre. Me perco no tempo-espaço da viagem, flashes inconsistentes da festa pipocam na minha vista com você, Wally, incrustada na paisagem. E debando no inconsciente, pássaro livre.",
				"Lentamente apoio minha cabeça sobre o meu braço estendido e me banho dos teus olhos e do toque rítmico dos seus dedos na minha mão.",
				"Sinto todos os olhares à nossa volta. Percebo que somos foco da atenção. Observo os cochichos, risadas, conferidas, cutucadas. Nos vejo destoantes, contraditórios, opostos. Ignoro tudo e me absorto em nós, o fluxo contrário dos outros passageiros.",
				"Deixo minha vista turvar à escuridão total, enquanto formulo sua imagem na minha mente. Explosão completa de cores e sentimentos, sons diversos e cheiros doces. No centro, emanando e absorvendo, o silêncio branco da fragrância que já tanto conheço e o calor abraço do seu peito!",
				"Demoro-me anos, milhas, ambulando nesse meu nosso paraíso virtual.",
				"Você puxa minha mão me tirando do seu transe, me sorri um sorriso pontual e me informa que descemos na próxima estação.",
				"Soltamos os dedos e desperto. Saimos em briga para a fuga. E o sonho acaba."
		]),
		("Entrada: Escreva um texto sobre um casal no metrô voltando de uma festa, por favor.", [
				"Noite adentro, a cidade pulsava com a energia das luzes e o calor da celebração. Um casal, envolto em roupas elegantes e sorrisos radiantes, encontrava-se no metrô, retornando de uma festa que ficaria marcada em suas memórias. A carruagem subterrânea, repleta de passageiros cansados e festivos, ecoava o zumbido suave dos trilhos.",
				"Sentados lado a lado, Maria e João compartilhavam risos sussurrantes enquanto observavam as pessoas ao redor. A luz difusa do vagão destacava as cores sutis de seus trajes festivos. Maria, com um vestido longo que cintilava como as estrelas da noite, segurava um pequeno buquê de flores que João lhe dera na festa.",
				"Os olhos deles ainda brilhavam com a alegria da noite, repleta de danças, músicas e encontros com amigos. As memórias da pista de dança, dos risos compartilhados e dos momentos especiais durante a festa dançavam em suas mentes enquanto o metrô avançava pelas entranhas da cidade.",
				"Ao redor, outros passageiros pareciam imersos em seus próprios pensamentos ou exaustos pela noite vivida. No entanto, o casal permanecia conectado, trocando olhares cúmplices e sorrisos que falavam mais do que palavras. A proximidade física no espaço limitado do metrô tornava ainda mais evidente o vínculo especial entre eles.",
				"Enquanto as estações se sucediam, Maria recostou a cabeça no ombro de João, desfrutando da sensação de proximidade e cumplicidade. O barulho monótono dos trilhos contrastava com a agitação da noite, criando uma atmosfera íntima no interior do vagão.",
				"A cada estação que passavam, o casal recordava momentos da festa: as risadas, os brindes, os abraços calorosos. O metrô, como um elo entre o efêmero da festa e a realidade cotidiana, testemunhava a transição suave de uma noite especial para o aconchego do retorno ao lar.",
				"Assim, entre suspiros e olhares apaixonados, Maria e João deixavam para trás a agitação da festa, levando consigo as lembranças de uma noite mágica enquanto o metrô os conduzia de volta ao seu mundo cotidiano, onde o amor florescia como uma flor noturna em meio ao silêncio da cidade adormecida."
		]),
		("Entrada: Reescreva, considerando: - a festa durou a noite toda e eles estão voltando de manhã - o metrô está lotado e eles tem que ficar de pé - não dê nome aos personagens", [
				"Ao romper da manhã, um casal, envolto em vestes elegantes e sorrisos cansados, encontra-se no metrô, retornando de uma festa que se estendeu pela noite. A carruagem subterrânea, repleta de passageiros exaustos e festivos, ecoa os sons abafados dos trilhos.",
				"De pé no vagão lotado, o casal compartilha risos discretos enquanto observa as pessoas ao redor. A luz fria do metrô destaca as nuances desgastadas de seus trajes festivos. Ela segura um pequeno buquê de flores, um resquício da festa noturna que agora se desvanece na luz do dia.",
				"Os olhos deles ainda refletem a alegria da noite passada, permeada por danças e músicas que agora são lembranças distantes. As memórias da pista de dança, dos risos compartilhados e dos momentos especiais durante a festa permeiam seus pensamentos enquanto o metrô avança pelos túneis subterrâneos.",
				"Os demais passageiros parecem envolvidos em seus próprios pensamentos ou cansados pelo longo período de celebração. Contudo, o casal permanece unido, trocando olhares furtivos e sorrisos que expressam mais do que palavras. O aperto do espaço limitado do metrô evidencia ainda mais o vínculo especial entre eles.",
				"À medida que as estações se sucedem, o casal recorda momentos da festa: os risos, os brindes, os abraços calorosos. O metrô, como uma ponte entre o efêmero da festa e a rotina diária, testemunha a transição gradual de uma noite especial para a normalidade da manhã urbana.",
				"Assim, entre bocejos e trocas de olhares sonolentos, o casal deixa para trás a efervescência da festa, levando consigo as lembranças de uma noite prolongada enquanto o metrô os conduz de volta à sua realidade cotidiana, onde o amor persiste como uma luz tênue diante da luminosidade implacável do novo dia."
		]),
		("Entrada: Reescreva considerando: - dê foco nos pensamentos de um deles, que admira o outro - inicie esses pensamentos com o toque das mãos sobre a barra do metrô - encerre a história com ele saindo dos pensamentos para descer do metrô", [
				"O metrô, abarrotado e pulsante, servia como palco para a silenciosa dança dos cansados passageiros. Entre eles, um casal destacava-se pela elegância e pelos sorrisos que, mesmo cansados, teimavam em permanecer. Enquanto a carruagem avançava, a mão dela encontrou a barra de apoio, um toque suave que iniciou uma sinfonia silenciosa nos pensamentos dele.",
				"Ele observava, embevecido, como a luz do metrô delineava os contornos suaves do rosto dela, ressaltando a beleza despretensiosa que persistia mesmo depois de uma noite inteira de celebração. Seus olhos, ainda refletindo o brilho da festa, capturavam a essência daquela jornada noturna compartilhada.",
				"A mente dele se perdia nos labirintos dos pensamentos, onde as memórias da festa se misturavam à imagem dela, uma constante fonte de encanto. O toque das mãos, apesar de simples, desencadeou um turbilhão de sentimentos. Lembrava-se das risadas compartilhadas, dos olhares cúmplices e da suavidade da noite que parecia se prolongar quando estavam juntos.",
				"Enquanto o metrô avançava, ele se via absorto na contemplação do que tinham vivido, como se cada estação fosse um capítulo a mais na narrativa daquela noite única. O barulho dos trilhos transformava-se em uma melodia suave, acompanhando seus devaneios apaixonados.",
				"Entretanto, a realidade do momento não tardou a se impor. As estações se sucediam, e a cidade despertava lentamente. Com um suspiro melancólico, ele desceu dos devaneios para encarar a dura realidade: a necessidade de sair do metrô. O toque suave da mão dela na barra foi o último acorde da sinfonia que, mesmo chegando ao fim, deixou uma melodia suave e eterna em seus corações."
		]),
		("Entrada: Reescreva considerando: - eles são os únicos no metrô que vieram da festa - as outras pessoas estão no caminho do trabalho - eles saem do metrô juntos quando ela o avisa que chegaram na estação", [
				"No cenário deserto do metrô matutino, um casal destacava-se entre os viajantes que se moviam em direção ao trabalho, vestígios de uma noite de festa ainda presentes em seus semblantes. A carruagem, agora silenciosa e vazia em sua maioria, tornava-se o palco íntimo de um retorno solitário de uma celebração que parecia ter durado uma eternidade.",
				"Enquanto o metrô seguia seu curso, eles eram os únicos a trazer consigo as lembranças de risos compartilhados, danças e momentos especiais. Seus olhares cansados, porém repletos de uma cumplicidade silenciosa, encontravam conforto na presença um do outro.",
				"Enquanto ela segurava a barra de apoio, os pensamentos dele se perdiam na contemplação da noite passada. O brilho da festa ainda se refletia em seus olhos, mas a realidade da rotina diária começava a se impor. Ao seu redor, as expressões dos outros passageiros denunciavam a pressa e a seriedade do cotidiano que os aguardava.",
				"À medida que o metrô se aproximava da estação, ela quebrou o silêncio ao avisar que era hora de descerem. O casal, ainda imerso na aura da noite anterior, deixou a carruagem juntos, emergindo para a estação enquanto a cidade despertava para mais um dia de obrigações.",
				"Enquanto as outras pessoas apressavam-se em direção aos seus destinos, o casal caminhava lado a lado pelas plataformas vazias. Ela, com a doçura de quem partilhou momentos especiais, apertou levemente sua mão, como se transmitisse um agradecimento silencioso por uma noite que, mesmo sendo passado, continuaria a ecoar em seus corações. E assim, entre a multidão que se dirigia ao trabalho, eles se tornaram dois pontos de luz, carregando consigo as lembranças de uma celebração que os fez escapar, ainda que brevemente, das obrigações do dia a dia."
		]),
		("Entrada: Reescreva considerando: - as mãos deles se tocam dentro do vagão, ao segurarem a barra - o trem está cheio de pessoas - elabore mais os pensamentos dele ao olhar para ela", [
				"No meio do vagão lotado do metrô matutino, as mãos deles se tocaram de maneira sutil ao segurarem a mesma barra de apoio. Entre a multidão que se dirigia ao trabalho, o toque casual tornou-se um elo efêmero, mas significativo, entre os dois. As expressões cansadas dos outros passageiros contrastavam com a atmosfera de cumplicidade que se desenhava entre eles.",
				"Enquanto o trem seguia seu percurso, os olhos dele buscavam refúgio nos traços suaves do rosto dela, iluminados de maneira tênue pela luz do vagão. A noite de festa ainda reverberava em seus pensamentos, e ele se viu capturado pela imagem dela, como se cada detalhe fosse uma pincelada que delineava as memórias recentes.",
				"O brilho dos olhos dela, reflexo da alegria compartilhada, era como um farol que o guiava em meio à rotina cinzenta da manhã. As risadas, os gestos, tudo parecia ecoar dentro dele, criando uma sinfonia particular que se misturava ao burburinho do metrô.",
				"Ao redor, o vaivém das pessoas parecia um borrão, mas ela permanecia nítida em sua mente. O toque contínuo de suas mãos, ainda entrelaçadas na barra de apoio, funcionava como um lembrete constante da conexão que compartilhavam. Em meio ao tumulto, o casal se encontrava imerso em um mundo próprio, onde as responsabilidades diárias cediam espaço às lembranças da noite anterior.",
				"À medida que se aproximavam da estação, ele foi despertado dos pensamentos pelo aviso dela de que era hora de descer. O toque suave das mãos se desfez, mas a lembrança daquele instante perduraria. Juntos, eles emergiram do vagão, atravessando a multidão que se dispersava. Ela lançou-lhe um sorriso, e, por um breve momento, as obrigações cotidianas pareceram distantes, enquanto a magia da noite persistia nos ecos da estação de metrô."
		]),
		("Entrada: Reescreva considerando: - escreva em segunda pessoa - não defina os gêneros dos personagens", [
				"No apertado vagão do metrô matutino, tuas mãos encontram-se de maneira sutil ao segurar a barra de apoio. Em meio à multidão que se dirige ao trabalho, esse toque efêmero torna-se um elo, breve mas significativo, entre vocês. As expressões cansadas dos outros passageiros contrastam com a atmosfera de cumplicidade que se desenha entre ambos.",
				"Enquanto o trem avança em seu percurso, teus olhos buscam refúgio nos traços suaves do rosto do outro, iluminados tenuemente pela luz do vagão. A noite de festa ainda ressoa em teus pensamentos, e te vês cativado pela imagem do outro, como se cada detalhe fosse uma pincelada delineando as memórias recentes.",
				"O brilho nos olhos do outro, reflexo da alegria compartilhada, as risadas, os gestos — tudo parece ecoar dentro de ti, criando uma sinfonia particular que se mistura ao burburinho do metrô. Em meio ao movimento frenético das pessoas ao redor, a barra de apoio torna-se um ponto de conexão constante, lembrando-te da união que compartilham.",
				"À medida que a estação se aproxima, és despertado dos pensamentos pelo aviso do outro de que é hora de descer. O toque suave das mãos se desfaz, mas a lembrança desse instante persistirá. Juntos, emergem do vagão, atravessando a multidão dispersa. O outro lança um sorriso, e, por um breve momento, as obrigações diárias parecem distantes, enquanto a magia da noite insiste nos ecos da estação de metrô."
		]),
		("Entrada: Reescreva considerando: - escreva do ponto de vista de um deles, não de um terceiro - aumente o devaneio gerado pela situação", [
				"No abarrotado vagão do metrô matutino, nossas mãos se encontram de maneira sutil ao segurar a barra de apoio. Entre a multidão que se desloca para o trabalho, esse toque efêmero transforma-se em um elo, breve mas significativo, entre nós. As expressões cansadas dos outros passageiros contrastam com a atmosfera de cumplicidade que se desenha entre nós dois.",
				"Enquanto o trem prossegue em seu trajeto, meus olhos buscam refúgio nos traços suaves do teu rosto, iluminados tenuemente pela luz do vagão. A noite de festa ainda ecoa em meus pensamentos, e me vejo cativado pela tua imagem, como se cada detalhe fosse uma pincelada delineando as memórias recentes.",
				"O brilho nos teus olhos, reflexo da alegria compartilhada, as risadas, os gestos — tudo parece ecoar dentro de mim, criando uma sinfonia particular que se mistura ao burburinho do metrô. Em meio ao movimento frenético das pessoas ao nosso redor, a barra de apoio torna-se um ponto de conexão constante, lembrando-me da união que compartilhamos.",
				"À medida que a estação se aproxima, sou despertado dos pensamentos pelo teu aviso de que é hora de descer. O toque suave das nossas mãos se desfaz, mas a lembrança desse instante persistirá. Juntos, emergimos do vagão, atravessando a multidão dispersa. Teu sorriso lança uma luz suave sobre o ambiente, e, por um breve momento, as obrigações diárias parecem distantes, enquanto a magia da noite insiste nos ecos da estação de metrô."
		]),
		("Entrada: Reescreva considerando: - aumente o devaneio - foque o devaneio nas lembranças da noite - foque nos detalhes de roupa e maquiagem gastos pela noitada", [
				"No congestionado vagão do metrô matutino, nossas mãos se entrelaçam suavemente ao buscar apoio na barra. Em meio à massa de passageiros que se apressam para o trabalho, esse toque fugaz se transforma em um elo, breve mas profundo, entre nós dois. As expressões fatigadas dos demais passageiros contrastam vividamente com a cumplicidade que floresce entre nós.",
				"Enquanto o trem desliza pelos trilhos, meu olhar se perde nos detalhes desgastados de tua roupa e maquiagem. As marcas da noitada estão presentes, como vestígios orgulhosos de uma celebração que durou até altas horas. O brilho nos teus olhos, mesmo sob a luz tênue do vagão, revela um reflexo da alegria compartilhada e das lembranças da noite passada.",
				"Cada detalhe da tua indumentária conta uma história: o vestido que ainda reluz com os resquícios da pista de dança, os sapatos que testemunharam passos ritmados e as nuances de uma maquiagem que desafiou o tempo. Esses traços, agora desgastados, são como vestígios de uma jornada noturna que se desenrolou em tons vibrantes.",
				"Enquanto nos mantemos unidos pela barra de apoio, meu pensamento mergulha mais fundo nas lembranças da noite. Revivo as risadas compartilhadas, os gestos afetuosos, as danças que nos envolveram. O burburinho do metrô torna-se um suave pano de fundo para a sinfonia de memórias que ressoa em minha mente.",
				"À medida que a estação se aproxima, és tu que me trazes de volta à realidade, indicando que é hora de descer. O toque suave de nossas mãos se desfaz, mas a lembrança persiste, envolvendo-me como uma canção que insiste em ecoar. Juntos, emergimos do vagão, atravessando a multidão dispersa. Teu sorriso, agora mais suave, carrega consigo os vestígios da noite vivida, e, por um breve momento, as obrigações diárias parecem suspensas, enquanto a magia da noite insiste nos ecos da estação de metrô."
		]),
	]
}

textos=[
	# ("formato_minimo","Formato Mínimo",11,),
	# ("meu_melhor_sorriso","Meu melhor Sorriso",11,),
	("mataram_os_poetas","Mataram os poetas",11, "https://www.instagram.com/sarraf_miguel/p/C6bqvxyuVLM/"),
	("ouroboros","Ouroboros",11, "https://www.instagram.com/p/C4c7SVHutD0/?igsh=MTM4OG56ZXBmYzB5cw=="),
	("prova_de_carinho","Prova de carinho",8, "https://www.instagram.com/p/C3DXptvuSg6/?igsh=dTk0d2p2c3J5NThh"),
	("fila_de_fosforos","Fila de fósforos",6, "https://www.instagram.com/p/C1r0sJ1OqD9/?igsh=NWIwM3JwcmYzd25i"),
	("cais","Cais",12, "https://www.instagram.com/p/C0hJJqyulgf/?igsh=ZmU0M2FwcHppNWZx"),
	("desventura_em_paralelo","Desventura em paralelo",12, "https://www.instagram.com/p/CzT8U7bukuu/?igsh=ZWZpdG16MXUzOTd6"),
	("ja_nao_me_tange","",7, "https://www.instagram.com/p/Cx8ZPgSufei/?igsh=MWdwNzlidnB1dXk4dw=="),
	("metro","Metrô",5, "https://www.instagram.com/p/Cwdw4CEOvWK/?igsh=eDl0bnJudnZucWQ4"),
	("endemia","Endemia",7, "https://www.instagram.com/p/CvSoz0DuAZ3/?igsh=M3IycmIycHV5a2Ry"),
]
